keys:
  - &all-keys
    - &dns2 age1qeyj80q9q72j5kdsa3yk8mtk6nnzzl43r2dmq35yclg4ygqaqvhqdek7rf
    - &remote-builder age1lz3hvew4wmfz7s4ta2curnfh5yej99cqjrccxuvu7yuj2h9c9sksctcn2q
    - &dns age1vhs4zsxaxe25t2w5s7dgq9w22phqfhl0059rlmhl8drxzj5xhctss5fpm7
    - &msaxena-keys >-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMDUuPzOBdRwbr6st5HJ4MveSMM6QvrjRzqF5FVLfS5 msaxena@Mayurs-MacBook-Pro.local,
      age1yubikey1qttjmkaf095gdjx7gd53440rely62smf2sk5t6w2wtmgn73cf84x5w5sm25,
      age1yubikey1qtz5nnzkpy943ynjywc3lntapsa9yx859gqsh05rkcyvnagtzhp76hq8g20

creation_rules:         
  - path_regex: secrets/common.yaml$
    key_groups:
      - age: *all-keys

  - path_regex: secrets/msaxena.yaml$
    age: *msaxena-keys
