keys:
  - &all-keys
    - &overseerr age1jcanh95tynwqxcqtxyye45ydx9adznsnwqml6r55m693shy84aesxkgu07
    - &homepage age18qkjke5gwtzmpydy6hh8z9kk9y8k8tjdnnz8zu28p2d8q03x35kqu7e2m9
    - &sabnzbd age1tjskj27vva0u9h3uejnp5scgpmz7ut36ffaqzg59sld6nsv0rcnq22jex6
    - &actualbudget age17tezfl457fm3cd9mzrcyqsa8we23w2fhslcurk8ul56f6s36t55sgwjq0r
    - &dns age124f9wlylq6hn9w6hcmyt7s4lg8vljvd96v62p5gh2u2zjuu9z98qvzr5rg
    - &nix-builder age1w6sygurulvf8p6n2avxfknnyglet5g5wulevh2cgypa7h4lssc7qn3g0hf
    - &msaxena-keys >-
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMDUuPzOBdRwbr6st5HJ4MveSMM6QvrjRzqF5FVLfS5 msaxena@Mayurs-MacBook-Pro.local,
      age1yubikey1qttjmkaf095gdjx7gd53440rely62smf2sk5t6w2wtmgn73cf84x5w5sm25,
      age1yubikey1qtz5nnzkpy943ynjywc3lntapsa9yx859gqsh05rkcyvnagtzhp76hq8g20

creation_rules:         
  - path_regex: secrets/common.yaml$
    key_groups:
      - age: *all-keys

  - path_regex: secrets/msaxena.yaml$
    age: *msaxena-keys

  - path_regex: secrets/homepage-dashboard-secrets.env$
    key_groups:
      - age: 
        - *msaxena-keys
        - *homepage
