keys:
  - &all-keys
    - &msaxena-keys >-
      age1yubikey1qttjmkaf095gdjx7gd53440rely62smf2sk5t6w2wtmgn73cf84x5w5sm25,
      age1yubikey1qtz5nnzkpy943ynjywc3lntapsa9yx859gqsh05rkcyvnagtzhp76hq8g20,
      age17meesgev7v9xu4xadt6e3qg03umvtzdthkzlv6zwg8rvp8jjedhstxc7gu

creation_rules:         
  - path_regex: secrets/common.yaml$
    key_groups:
      - age: *all-keys

  - path_regex: secrets/msaxena.yaml$
    age: *msaxena-keys
          
