---
- name: Start the guest agent
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    enabled: true
    state: started
  become: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
