---
name: Generate LXC Images
on:
    push:
        branches:
            - main
        tags:
            - prod
permissions:
    contents: write
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4 #checkout the repo
                with:
                    fetch-depth: 1
            
            -   name: Install nix
                uses: cachix/install-nix-action@v24
                with:
                    github_access_token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Generate NixOS configuration
                run: |
                    nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#base-lxc | {
                        read path
                        echo "BUILD_PATH=$path" >> $GITHUB_ENV
                    }
            
            -   name: Release
                uses: softprops/action-gh-release@v2
                if: github.ref_type == 'tag'
                with:
                    files: ${{ env.BUILD_PATH }}
            