---
name: Generate LXC Images
on:
    push:
        tags:
            - prod
            - nightly
permissions:
    contents: write
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4 #checkout the repo
                with:
                    fetch-depth: 1
            
            -   name: Install nix
                uses: cachix/install-nix-action@v24
                with:
                    github_access_token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Generate standard NixOS configuration
                run: |
                    nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#base-lxc | {
                        read path
                        FILENAME="$(basename $path)"
                        RELEASE_PATH="${{ github.workspace }}/nixos-proxmox-lxc-standard.tar.xz"
                        cp $path $RELEASE_PATH
                        echo "RP1=$RELEASE_PATH" >> $GITHUB_ENV
                    }
            
            -   name: Generate impermanent NixOS configuration
                run: |
                    nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#base-lxc-impermanent | {
                        read path
                        FILENAME="$(basename $path)"
                        RELEASE_PATH="${{ github.workspace }}/nixos-proxmox-lxc-impermanent.tar.xz"
                        cp $path $RELEASE_PATH
                        echo "RP2=$RELEASE_PATH" >> $GITHUB_ENV
                    }

            -   name: Generate standard NixOS configuration with remote builder configured
                run: |
                    nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#base-lxc-remote | {
                        read path
                        FILENAME="$(basename $path)"
                        RELEASE_PATH="${{ github.workspace }}/nixos-proxmox-lxc-standard-remotebuild.tar.xz"
                        cp $path $RELEASE_PATH
                        echo "RP3=$RELEASE_PATH" >> $GITHUB_ENV
                    }

            -   name: Generate impermanent NixOS configuration with remote builder configured
                run: |
                    nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#base-lxc-impermanent-remote | {
                        read path
                        FILENAME="$(basename $path)"
                        RELEASE_PATH="${{ github.workspace }}/nixos-proxmox-lxc-impermanent-remotebuild.tar.xz"
                        cp $path $RELEASE_PATH
                        echo "RP4=$RELEASE_PATH" >> $GITHUB_ENV
                    }
            
            -   name: Release
                uses: softprops/action-gh-release@v2
                if: github.ref_type == 'tag'
                with:
                    files: |
                        ${{ env.RP1 }}
                        ${{ env.RP2 }}
                        ${{ env.RP3 }}
                        ${{ env.RP4 }}
            
